# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rant',
            old_name='time_created',
            new_name='created',
        ),
    ]
