# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 23:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rants', '0003_auto_20171225_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rant',
            name='created_by',
            field=models.ForeignKey(default='anonymous', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
