# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rants', '0006_auto_20171225_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='rant',
            name='catigory',
            field=models.CharField(choices=[('E', 'Everyday Living'), ('P', 'Politics'), ('G', 'Religion'), ('R', 'Relationship'), ('S', 'Sex'), ('O', 'Other')], default='Everyday Living', max_length=1),
        ),
    ]
