# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rants', '0013_auto_20171227_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rant',
            name='body',
            field=models.TextField(max_length=400),
        ),
    ]
