# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rants', '0015_auto_20171228_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default='text', max_length=400),
            preserve_default=False,
        ),
    ]
