# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rants', '0017_auto_20171230_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rant',
            name='body',
            field=models.TextField(),
        ),
    ]
