---
- hosts: all
  become: true
  tasks:
    - name: update ubuntu
      apt:
        upgrade: dist
        update_cache: yes

    - name: Install packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - python3
        - nginx
        - python3-pip
        - python3-virtualenv
        update_cache: yes